name: Test native code

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - name: Run native tests
      working-directory: ./app/src/main/jni/tests
      run: make run_tests
